baseurl = "https://davidrallen.com/"
languageCode = "en-us"
title = "Resume"
theme = "helix"
disqusShortname = "doctorallen"
SectionPagesMenu = "main"
preserveTaxonomyNames = true
[[menu.main]]
    name = "Resume"
    identifier = "resume"
    url = "/"
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "GitHub"
    weight = 100
    identifier = "github"
    url = "https://github.com/doctorallen/"
[taxonomies]
tag = "tags"
category = "categories"
series = "series"
